INSERT INTO CARCENTERADMIN.MANO_DE_OBRA 
(SERVICIO       ,
DESCRIPCION     ,
PRECIO_MAXIMO   , 
PRECIO_MINIMO   ,
PRECIO_TOTAL ) 
VALUES (
'Cambio de aceite'       ,
'Cambia de aceite , en conjunto de un aceite'     ,
100000   , 
100000   ,
100000
);
/
INSERT INTO CARCENTERADMIN.MANO_DE_OBRA 
(SERVICIO       ,
DESCRIPCION     ,
PRECIO_MAXIMO   , 
PRECIO_MINIMO   ,
PRECIO_TOTAL ) 
VALUES (
'Cambio de aceite'       ,
'Cambia de aceite , en conjunto de un aceite'     ,
100000   , 
100000   ,
100000
);
/
INSERT INTO CARCENTERADMIN.MANO_DE_OBRA 
(SERVICIO       ,
DESCRIPCION     ,
PRECIO_MAXIMO   , 
PRECIO_MINIMO   ,
PRECIO_TOTAL ) 
VALUES (
'Cambio de aceite'       ,
'Cambia de aceite , en conjunto de un aceite'     ,
100000   , 
100000   ,
100000
);
/